# Read the Docs configuration file
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    install:
      - pip install .[doc]

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
  
